name: ISI Burger CI/CD

on:
  push:
    branches:
      - nom_prenom_burger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Pull du code depuis GitHub
        uses: actions/checkout@v3

      - name: 🐘 Installation de PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql

      - name: 📦 Installation des dépendances Laravel
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: 📋 Configuration de l'environnement
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: 🐳 Création de l'image Docker
        run: |
          docker build -t isi_burger:latest .
